name: IncomeSell
description: 'Main sell plugin for the IncomeMC Generator server'
version: '${version}'
main: dev.lyric.income.sell.IncomeSell
api-version: '1.21.11'
load: POSTWORLD
authors: [ Lyric/Fusezion ]
